# stats available at
# https://travis-ci.org/fancycode/pylzma
language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "nightly"

env:
  - CC=/usr/lib/ccache/gcc CXX=/usr/lib/ccache/g++

addons:
  apt:
    packages:
    - ccache

cache:
  directories:
    - $HOME/.ccache

install:
  - wget --no-check-certificate -O tests/data/ux.stackexchange.com.7z https://archive.org/download/stackexchange/ux.stackexchange.com.7z

script: 
  - python setup.py test
